<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ProductUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name'=>'nullable|string|min:3',
            'price'=>'nullable|numeric|min:10'
        ];
    }

    public function messages()
    {
        return [

            'name.string'=>"အမည်ထည့်ရန်လိုအပ်သည်။",
            'price.numeric'=>"ဈေးနှုန်းသည်ဂဏန်းဖြစ်ရမည်။"
        ];
//        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
